version: "2.1"

services:

  maven-event-driven-framework-app:
    build:
      context: .
      dockerfile: .mvn/Dockerfile
    volumes: ["maven-app-data:/home/appuser"]
    networks: [backing-services]
#    ports: ["8080:8080"]
#    restart: unless-stopped
#    mem_limit: 209715200 # container limit: 200Mb (200 * 1024 * 1024)

volumes:
  maven-app-data: {}

networks:
  backing-services:
    driver: bridge
